name: Unit Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build Project
      run: make
    - name: Build and Run Test
      run: make test
      
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Format Project
      run: make fmt
    - name: Check Format
      run: |
        dif=$(git diff)
        echo $dif
        test $(echo -n $dif | wc -l) -eq 0

