name: Unit Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check format
      run: cargo fmt -- --check
    - name: Build Project
      run: cargo build --verbose
    - name: Build and Run Test
      run: cargo test --verbose

